baseURL: "https://nslythe.io"
title: "nslythe"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "nslythe"
  description: ""
  keywords: [Blog, Portfolio]
  author: nslythe
  # author: ["Me", "You"] # multiple authors
  images: "https://www.gravatar.com/avatar/31d5d460793a1f4966363c368f1a6ec5?s=200"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://www.gravatar.com/avatar/31d5d460793a1f4966363c368f1a6ec5?s=200"
    favicon16x16: "https://www.gravatar.com/avatar/31d5d460793a1f4966363c368f1a6ec5?s=16"
    favicon32x32: "https://www.gravatar.com/avatar/31d5d460793a1f4966363c368f1a6ec5?s=32"
#    apple_touch_icon: "<link / abs url>"
#    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "nslythe"
    Content: ""

#  socialIcons:
#    - name: twitter
#      url: "https://twitter.com/"
#    - name: stackoverflow
#      url: "https://stackoverflow.com"
#    - name: github
#      url: "https://github.com/"

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/nslythe/nslythe/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
#    lineNos: true
    style: monokai
